# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pub_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.Publication'),
        ),
    ]
