# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication_MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book_mm',
            name='pub_id',
            field=models.ManyToManyField(to='app1.Publication_MM'),
        ),
    ]
